[project]
name = "aml25-hw2"
version = "1.0.0"
description = "AML25 Homework 2"
authors = [
	{name = "bzy", email = "bzy.cirno@gmail.com"}
]
requires-python = ">=3.8"
dependencies = [
    "torch",
    "torchvision",
    "pandas",
    "tqdm",
    "numpy",
    "torch_ema",
    "sklearn"
]